# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0
# docker-compose up --build
# docker-compose up -d
# docker-compose up --build -d
# docker-compose down
# docker-compose down -v

version: '3.7'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    networks:
      - moodle-network
    environment:
      - MARIADB_ROOT_PASSWORD=adminroot
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:latest
    ports:
      - '80:8080'
      - '443:8443'
    networks:
      - moodle-network
    environment:
      - BITNAMI_DEBUG=true
      - MOODLE_DATABASE_TYPE=mariadb
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_SITE_NAME=BitnamiMoodle
      - MOODLE_LANG=fr
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=biov@Moodle24
      - MOODLE_EMAIL=sejloxaag.se@gmail.com
      - MOODLE_SMTP_HOST=smtp.gmail.com
      - MOODLE_SMTP_PORT_NUMBER=587
      - MOODLE_SMTP_USER=sedodigittech229@gmail.com
      - MOODLE_SMTP_PASSWORD=nijxretwneifasmm
      - MOODLE_SMTP_PROTOCOL=smtp
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local

networks:
  moodle-network:
    driver: bridge